# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0002_auto_20161217_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='failed_tries',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='letters',
            field=models.ManyToManyField(to='hangman.Letters'),
        ),
    ]
