# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0003_auto_20161218_2318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Letters',
            new_name='Letter',
        ),
    ]
