# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0004_auto_20161218_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='letter',
            name='points',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='failed_tries',
            field=models.IntegerField(default=0),
        ),
    ]
