# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0005_auto_20161219_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='points',
            field=models.IntegerField(default=100),
        ),
    ]
